### ISSUE TITLE
Hero Image

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Philosophy#6]
Hey @ZMcGroarty when you get a chance can you size and red hue the hero image for me? Thanks!

**Comment by CVE82** [comment]
It's in the media library

**Comment by ZMcGroarty** [comment]
Here you go!

![hero_philosophy-min](https://user-images.githubusercontent.com/15017242/32788227-a747c07c-c926-11e7-9163-c68acc2d1a70.png)

**Comment by CVE82** [comment]
Awesome thank you!
